<?php

// configuracoes de perfil
define("TAMANHO_MINIMO_SENHA", 8);
define("COOKIES_DIAS_EXISTE", 30);
define("IDADE_MINIMA_CADASTRO", 16);
define("TAMANHO_ESCALA_IMG_PERFIL", 640);
define("TAMANHO_ESCALA_IMG_PERFIL_MINIATURA", 128);
define("TAMANHO_MAXIMO_CARACTERES_SOBRE_PERFIL_EXIBIR", 800);
define("TAMANHO_MAXIMO_NOME_USUARIO_CARACTERES", 50);
define("ESCALA_IMAGEM_ALBUM", 1024);
define("ESCALA_IMAGEM_ALBUM_MINIATURA", 768);

?>